#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
extdoc_probe.py -- 在红区本地把 Cadence extUser.pdf 拆成可外带的小块答案。

设计前提（红区）：
  * 只用标准库（zlib/re/subprocess）。python 2.7 和 3.x 都能跑。
  * 不装任何包（site-packages 只读）。
  * PDF 20+MB，一次只能带出 ~50KB 文字 -> 输出按 48000 字节切块。

用法（PDF 路径：--pdf 或 $EXTDOC_PDF，不再内置——见 PDF_DEFAULT）：
  python extdoc_probe.py build            # 一次性 PDF -> 纯文本缓存（留在红区）
  python extdoc_probe.py info             # 缓存有多大、哪种抽取器、文本可读吗
  python extdoc_probe.py toc              # 扫出全部 "-option" 词元 + 出现页码（小输出）
  python extdoc_probe.py ask              # 目录里所有待答字段，切块写 answers_NN.txt
  python extdoc_probe.py ask --only extract_type,output_xy --hits 3 --per-hit 1200
  python extdoc_probe.py grep multi_cpu   # 临时查任意词
  python extdoc_probe.py page 812 815     # 原样倒出某几页

只有 ask / grep / page / toc 的输出需要外带；build 产生的大文本留在红区。
"""

from __future__ import print_function
# Both of these exist because this file carries Chinese literals (the field
# table and every progress line) and the red-zone box's bare `python` is 2.7.
# Without unicode_literals, cmd_ask's "".join() mixes a byte str holding those
# literals with the unicode read back from the text cache -> UnicodeDecodeError
# on the main path. See _force_utf8_stdio for the other half.
from __future__ import unicode_literals

import os
import re
import sys
import zlib
import bisect
import subprocess

# The manual's location is a SITE COORDINATE, so it cannot live in a
# public repo -- redzone_scan.sh refuses it, and being uncommittable is
# exactly why this script was lost once already. Set EXTDOC_PDF, or pass
# --pdf.
PDF_DEFAULT = os.environ.get("EXTDOC_PDF", "")
WORK_DEFAULT = "./extdoc_work"
CHUNK_BYTES = 48000

IS_PY2 = sys.version_info[0] == 2


def _force_utf8_stdio():
    """The red-zone shell is usually LANG=C. Without this, the first Chinese
    thing this script prints raises UnicodeEncodeError -- on py3 too."""
    try:
        if IS_PY2:
            import codecs
            sys.stdout = codecs.getwriter("utf-8")(sys.stdout, errors="replace")
            sys.stderr = codecs.getwriter("utf-8")(sys.stderr, errors="replace")
        else:
            for h in (sys.stdout, sys.stderr):
                try:
                    h.reconfigure(encoding="utf-8", errors="replace")
                except AttributeError:
                    pass          # py3 < 3.7
    except Exception:
        pass


_force_utf8_stdio()


# --------------------------------------------------------------------------
# 待确认字段表：(key, [搜索词...], 我们到底想问什么)
# 来源 docs/refactor/catalog-quantus.json 里 confidence != certain 的条目，
# guess 的排在前面（先把预算花在最没底的上面）。
# --------------------------------------------------------------------------
FIELDS = [
    # (key, [search terms], what we actually want to know)
    #
    # GENERATED by scripts/refresh_extdoc_fields.py from options.yaml --
    # every row that still carries a `question:`. Do not edit by hand:
    # a list maintained here drifts from the catalog the moment a
    # question is answered, and then this script goes on asking things
    # nobody needs while missing the ones nobody has asked.
    # ---- quantus ----
    ('array_vias_spacing', ['-array_vias_spacing', 'array_vias_spacing'],
     'Can these take a number as well as "auto"?'),
    ('cap_component', ['-cap_component', 'cap_component'],
     'Are these the device names in your PDK? Must both tools agree?'),
    ('coupling_cap_threshold_absolute', ['-coupling_cap_threshold_absolute', 'coupling_cap_threshold_absolute'],
     'What value and unit do you normally use here?'),
    ('include_parasitic_res_model', ['-include_parasitic_res_model', 'include_parasitic_res_model'],
     'What does "comment" mean in your post-layout sim, and when is each of the three used?'),
    ('max_fracture_length', ['-max_fracture_length', 'max_fracture_length'],
     'What do you set this to for long RF transmission lines?'),
    ('metal_fill_type', ['metal_fill -type', '-metal_fill_type', 'metal_fill_type'],
     'Should the two flows really treat metal fill differently?'),
    ('output_form', ['output_db -type', '-output_form', 'output_form'],
     'Do you ever need an extracted view AND a DSPF from one run? Do you need SPEF?'),
    # ---- quantus(absent) ----
    ('extract_gate_diffusion_fringing_cap', ['-extract_gate_diffusion_fringing_cap', 'extract_gate_diffusion_fringing_cap'],
     'What is the default of -extract_gate_diffusion_fringing_cap, and is it superseded when the PDK device model already carries fringing?'),
    ('extract_via_cap', ['-extract_via_cap', 'extract_via_cap'],
     'What is the default of extract -extract_via_cap, and does it interact with -use_field_solver?'),
    ('global_nets_nets', ['global_nets', '-import_from_lvs', '-force_global_nets'],
     'What are the defaults and interaction rules of the four global_nets options, and how do they relate to the power_names / ground_names tables on the profile?'),
    ('inductance_nets_file', ['-inductance_nets_file', 'inductance_nets_file'],
     'What is the format of the inductance nets file, and is it mandatory for the rlc and rlck extract types?'),
    ('merge_parallel_via', ['-merge_parallel_via', 'merge_parallel_via'],
     'What is the documented default of filter_res -merge_parallel_via, and which flow is it?'),
    ('min_res_centering', ['-min_res_centering', 'min_res_centering'],
     'Is filter_res -min_res_centering a boolean or an enum, what is its default, and which flow does it apply to?'),
    ('strmout_hier_depth', ['strmout', 'hierarchy depth'],
     'Did your manual flow ever specify hierarchy depth, case handling or dot conversion?'),
    ('substrate_nets_file', ['-substrate_nets_file', 'substrate_nets_file'],
     'Is -substrate_nets_file required for the substrate_only and decoupled_to_substrate extract types?'),
    ('use_field_solver', ['-use_field_solver', 'use_field_solver'],
     'Which of the three -use_field_solver levels does an omitted line actually give us, and what does default_accuracy cost in runtime against high_accuracy?'),
    # ---- calibre ----
    ('erc_database', ['*lvsERCDatabase', '-lvs_erc_database', 'lvs_erc_database'],
     'Should ERC results be archived per run, and should they gate pass/fail?'),
    ('layout_db_name', ['*lvsLayoutPaths', '-strmFile', '-lvs_layout_paths', 'lvs_layout_paths'],
     'The old script exported <cell>.gds and let you choose the drop location (default dir / cwd / a named subdir). Do you still need those choices?'),
    ('lvs_abort_on_supply_error', ['*lvsAbortOnSupplyError', '-lvs_abort_on_supply_error', 'lvs_abort_on_supply_error'],
     'Turn it on? With those two supply-name lists in play, would a lot of blocks suddenly stop passing?'),
    ('lvs_connect_by_name', ['*cmnVConnectNamesState', '-connect_by_name', 'connect_by_name'],
     'Only "connect everything by name" and "connect nothing" exist today. Have you ever needed name-connection for supplies only?'),
    ('lvs_device_filter_enabled', ['*lvsDeviceFilterOptionsEnabled', '-lvs_device_filter_options_enabled', 'lvs_device_filter_options_enabled'],
     'What do AG / RC / RE / RG mean, and do you want filtering on?'),
    ('lvs_layout_device_filter_options', ['*lvsLayoutDeviceFilterOptions', '-lvs_layout_device_filter_options', 'lvs_layout_device_filter_options'],
     'What do AG / RC / RE / RG mean?'),
    ('lvs_license_wait_time', ['*cmnLicenseWaitTime', '-cmn_license_wait_time', 'cmn_license_wait_time'],
     'Is the license wait time in minutes?'),
    ('lvs_num_turbo', ['*cmnNumTurbo', '-cmn_num_turbo', 'cmn_num_turbo'],
     'Does your site have Hyperscaling licenses? How many Turbo cores?'),
    ('lvs_report_options', ['*lvsReportOptions', '-lvs_report_options', 'lvs_report_options'],
     'Which extra report sections do you normally need?'),
    ('lvs_run_hyper', ['*cmnRunHyper', '-cmn_run_hyper', 'cmn_run_hyper'],
     'Does your site have a Hyperscaling license at all?'),
    # ---- jivaro ----
    ('parasitic_res_model', ['rModel', '-jivaro_r_model', 'jivaro_r_model'],
     'Are these four device names right for your PDK, and must both tools agree?'),
    ('reduction_criterion', ['criterion', '-jivaro_criterion', 'jivaro_criterion'],
     'What other criteria does the Jivaro UI offer?'),
    # ---- si ----
    ('cdl_include_file', ['cdl_include_file', 'includeFile'],
     'Run si once and confirm the generated .src.net really carries the device subckt definitions. Do you ever need MORE than one CDL prepended?'),
    ('netlist_check_scale', ['checkScale', '-check_scale', 'check_scale'],
     'Does your Calibre deck expect meter or micron here?'),
    ('netlist_global_power_sig', ['globalPowerSig', '-global_power_sig', 'global_power_sig'],
     'Do your schematics always declare their own globals? Should the cell table grow a "power net" column to pair with the existing ground one?'),
    ('netlist_short_res', ['shortRES', '-short_res', 'short_res'],
     'Is a resistor shorted BELOW this value or above it? Is the unit ohms? Does it have to agree with the Calibre deck?'),
]


# --------------------------------------------------------------------------
# 1. PDF -> 文本
# --------------------------------------------------------------------------

def _which(prog):
    for d in os.environ.get("PATH", "").split(os.pathsep):
        p = os.path.join(d, prog)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p
    return None


def _run(cmd):
    try:
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p.communicate()
        return p.returncode
    except Exception:
        return 127


def _try_external(pdf, out):
    """按可靠性排序试外部工具。返回用上的工具名，全失败返回 None。"""
    cands = []
    if _which("pdftotext"):
        cands.append(("pdftotext",
                      ["pdftotext", "-layout", "-enc", "UTF-8", pdf, out]))
    if _which("gs"):
        cands.append(("ghostscript-txtwrite",
                      ["gs", "-q", "-dNOPAUSE", "-dBATCH", "-dSAFER",
                       "-sDEVICE=txtwrite", "-dTextFormat=3",
                       "-sOutputFile=" + out, pdf]))
    if _which("mutool"):
        cands.append(("mutool", ["mutool", "draw", "-F", "txt", "-o", out, pdf]))
    if _which("pdf2txt.py"):
        cands.append(("pdfminer", ["pdf2txt.py", "-o", out, pdf]))
    for name, cmd in cands:
        sys.stderr.write("  try %s ...\n" % name)
        rc = _run(cmd)
        if rc == 0 and os.path.isfile(out) and os.path.getsize(out) > 20000:
            return name
        if os.path.isfile(out) and os.path.getsize(out) <= 20000:
            os.remove(out)
    return None


_STR = re.compile(br"\((?:\\.|[^\\()])*\)", re.S)
_SHOW = re.compile(
    br"(\((?:\\.|[^\\()])*\))\s*(?:Tj|')"
    br"|\[((?:[^\[\]\\]|\\.)*)\]\s*TJ"
    br"|(T\*|Td|TD|BT|ET)", re.S)
_ESC = {b"n": b"\n", b"r": b"\r", b"t": b"\t", b"b": b"\b",
        b"f": b"\f", b"(": b"(", b")": b")", b"\\": b"\\"}


def _unescape(s):
    s = s[1:-1]
    out = []
    i, n = 0, len(s)
    while i < n:
        c = s[i:i + 1]
        if c == b"\\" and i + 1 < n:
            nx = s[i + 1:i + 2]
            if nx in _ESC:
                out.append(_ESC[nx])
                i += 2
                continue
            if nx.isdigit():
                j = i + 1
                while j < n and j < i + 4 and s[j:j + 1].isdigit():
                    j += 1
                try:
                    out.append(bytes(bytearray([int(s[i + 1:j], 8) & 0xFF])))
                except Exception:
                    pass
                i = j
                continue
            if nx == b"\n":
                i += 2
                continue
            out.append(nx)
            i += 2
            continue
        out.append(c)
        i += 1
    return b"".join(out)


_TJ_ITEM = re.compile(br"\((?:\\.|[^\\()])*\)|<[0-9A-Fa-f\s]*>|-?\d+(?:\.\d+)?")


def _hexstr(tok):
    h = re.sub(br"[^0-9A-Fa-f]", b"", tok)
    if len(h) % 2:
        h += b"0"
    try:
        return bytes(bytearray(int(h[i:i + 2], 16) for i in range(0, len(h), 2)))
    except Exception:
        return b""


def _content_to_text(data):
    out = []
    for m in _SHOW.finditer(data):
        if m.group(1):
            out.append(_unescape(m.group(1)))
        elif m.group(2) is not None:
            # 逐项走 TJ 数组：大的负 kerning 就是词间空格
            # （LaTeX / FrameMaker 排版常这么干，不补就会粘成一坨）
            for im in _TJ_ITEM.finditer(m.group(2)):
                tok = im.group(0)
                if tok[:1] == b"(":
                    out.append(_unescape(tok))
                elif tok[:1] == b"<":
                    out.append(_hexstr(tok))
                else:
                    try:
                        if float(tok) <= -100.0:
                            out.append(b" ")
                    except Exception:
                        pass
        else:
            if m.group(3) in (b"T*", b"Td", b"TD", b"ET"):
                out.append(b"\n")
    txt = b"".join(out)
    return re.sub(br"\n{3,}", b"\n\n", txt)


def _pure_python(pdf, out):
    """最后兜底：只靠 zlib 解 FlateDecode 内容流，硬扫 Tj/TJ。
    没有字体编码映射，subset 字体会出乱码 —— info 的可读性分数会告诉你。"""
    fh = open(pdf, "rb")
    raw = fh.read()
    fh.close()
    pages = []
    for m in re.finditer(br"stream\r?\n", raw):
        head = raw[max(0, m.start() - 800):m.start()]
        if b"/Image" in head or b"DCTDecode" in head or b"JPXDecode" in head:
            continue
        start = m.end()
        end = raw.find(b"endstream", start)
        if end < 0:
            continue
        data = raw[start:end]
        if b"FlateDecode" in head:
            try:
                data = zlib.decompress(data)
            except Exception:
                try:
                    data = zlib.decompressobj().decompress(data)
                except Exception:
                    continue
        elif b"/Filter" in head:
            continue
        if b"Tj" not in data and b"TJ" not in data:
            continue
        t = _content_to_text(data)
        if len(t.strip()) > 20:
            pages.append(t)
    fo = open(out, "wb")
    fo.write(b"\f".join(pages))
    fo.close()
    return len(pages) > 0


def cmd_build(args):
    pdf = args.get("pdf", PDF_DEFAULT)
    work = args.get("work", WORK_DEFAULT)
    if not os.path.isfile(pdf):
        die("找不到 PDF: %s  (用 --pdf 指定)" % pdf)
    if not os.path.isdir(work):
        os.makedirs(work)
    txt = os.path.join(work, "doc.txt")
    if os.path.isfile(txt) and not args.get("force"):
        print("已存在 %s（%.1f MB）。要重建加 --force" %
              (txt, os.path.getsize(txt) / 1048576.0))
        return
    print("PDF: %s  (%.1f MB)" % (pdf, os.path.getsize(pdf) / 1048576.0))
    tool = _try_external(pdf, txt)
    if tool is None:
        print("  外部工具都不可用/失败，回退纯 python 解析（可能有乱码）")
        if not _pure_python(pdf, txt):
            die("纯 python 回退也没提出文本。把 `which pdftotext gs mutool` 的结果发出来。")
        tool = "pure-python(degraded)"
    fh = open(os.path.join(work, "extractor.txt"), "w")
    fh.write(tool + "\n")
    fh.close()
    print("OK  抽取器=%s  ->  %s (%.1f MB)" %
          (tool, txt, os.path.getsize(txt) / 1048576.0))
    cmd_info(args)


# --------------------------------------------------------------------------
# 2. 缓存加载 / 页码
# --------------------------------------------------------------------------

def load(work):
    txt = os.path.join(work, "doc.txt")
    if not os.path.isfile(txt):
        die("还没建缓存。先跑：python %s build" % os.path.basename(sys.argv[0]))
    fh = open(txt, "rb")
    data = fh.read()
    fh.close()
    s = data.decode("utf-8", "replace")
    pages = s.split("\f")
    starts, off = [], 0
    for p in pages:
        starts.append(off)
        off += len(p) + 1
    return s, pages, starts


def readability(s):
    sample = s[:400000]
    if not sample:
        return 0.0
    good = 0
    for c in sample:
        if c.isalnum() or c in " .,-_()/\n\t:;=\"'":
            good += 1
    return good / float(len(sample))


def cmd_info(args):
    work = args.get("work", WORK_DEFAULT)
    s, pages, starts = load(work)
    ex = "?"
    p = os.path.join(work, "extractor.txt")
    if os.path.isfile(p):
        fh = open(p)
        ex = fh.read().strip()
        fh.close()
    r = readability(s)
    print("抽取器      : %s" % ex)
    print("文本大小    : %.1f MB" % (len(s) / 1048576.0))
    print("页数        : %d" % len(pages))
    print("可读性      : %.3f  (>0.90 好；<0.80 说明字体编码没解开，换抽取器)" % r)
    for probe in ("Quantus", "extraction", "output_db", "-decoupling_factor",
                  "extract_type", "command file"):
        print("  含 %-24s : %d 次" % (repr(probe), s.count(probe)))
    if r < 0.80:
        print("\n[!] 可读性偏低。把 `which pdftotext gs mutool acroread` 的输出发出来。")


# --------------------------------------------------------------------------
# 3. 查询
# --------------------------------------------------------------------------

def collapse(t):
    return re.sub(r"[ \t\x0b\r]+", " ", re.sub(r"\n{2,}", "\n", t)).strip()


DEF_KW = ("default", "specifies", "valid values", "choices", "the default",
          "possible values", "one of", "syntax")


def find_hits(pages, term, max_hits):
    """返回 [(score, page_no, line_no, 上下文原文)]，按 score 降序、同页去重。"""
    hits = []
    tl = term.lower()
    for pi, ptext in enumerate(pages):
        if tl not in ptext.lower():
            continue
        lines = ptext.split("\n")
        for li, line in enumerate(lines):
            low = line.lower()
            if tl not in low:
                continue
            st = line.strip()
            score = 1
            if st.lower().startswith(tl):
                score += 10          # 词条开头 = 多半是定义
            if re.match(r"^-?[\w_]+$", st):
                score += 3           # 独占一行
            nxt = " ".join(lines[li + 1:li + 4]).lower()
            for kw in DEF_KW:
                if kw in nxt or kw in low:
                    score += 4
                    break
            if len(st) > 200:
                score -= 2           # 正文长段落，多半只是顺带提一嘴
            hits.append((score, pi + 1, li + 1, "\n".join(lines[li:li + 14])))
    hits.sort(key=lambda x: (-x[0], x[1]))
    seen, out = set(), []
    for h in hits:
        if h[1] in seen:
            continue
        seen.add(h[1])
        out.append(h)
        if len(out) >= max_hits:
            break
    return out, len(hits)


class Chunker(object):
    def __init__(self, work, prefix, limit):
        self.work, self.prefix, self.limit = work, prefix, limit
        self.n, self.buf, self.size = 0, [], 0
        self.files = []

    def add(self, text):
        b = text.encode("utf-8", "replace")
        if self.size and self.size + len(b) > self.limit:
            self.flush()
        self.buf.append(text)
        self.size += len(b)

    def flush(self):
        if not self.buf:
            return
        self.n += 1
        path = os.path.join(self.work, "%s_%02d.txt" % (self.prefix, self.n))
        fh = open(path, "wb")
        fh.write(("".join(self.buf)).encode("utf-8", "replace"))
        fh.close()
        self.files.append((path, os.path.getsize(path)))
        self.buf, self.size = [], 0

    def report(self):
        print("写出 %d 个分块（每块 <= %d 字节）：" % (len(self.files), self.limit))
        for p, sz in self.files:
            print("  %s  %d bytes" % (p, sz))


def cmd_ask(args):
    work = args.get("work", WORK_DEFAULT)
    s, pages, starts = load(work)
    only = args.get("only")
    per_hit = int(args.get("per-hit", 700))
    max_hits = int(args.get("hits", 2))
    limit = int(args.get("budget", CHUNK_BYTES))
    fields = FIELDS
    if only:
        want = set(x.strip() for x in only.split(","))
        fields = [f for f in FIELDS if f[0] in want]
        missing = want - set(f[0] for f in fields)
        if missing:
            print("[!] 不认识的 key: %s" % ", ".join(sorted(missing)))
    ch = Chunker(work, "answers", limit)
    ch.add("# extUser.pdf 字段探查  (%d 字段, 每命中<=%dB, 每字段<=%d 命中)\n"
           % (len(fields), per_hit, max_hits))
    for key, terms, question in fields:
        blk = ["\n===== %s =====\n问: %s\n" % (key, question)]
        got = False
        for term in terms:
            hits, total = find_hits(pages, term, max_hits)
            if not hits:
                blk.append("  [%s] 0 命中\n" % term)
                continue
            got = True
            blk.append("  [%s] 共 %d 命中, 取前 %d:\n" % (term, total, len(hits)))
            for score, pg, ln, ctx in hits:
                c = collapse(ctx)
                if len(c) > per_hit:
                    c = c[:per_hit] + " ...[截断]"
                blk.append("  -- p.%d (score %d) --\n  %s\n" % (pg, score, c))
        if not got:
            blk.append("  ** 全部搜索词零命中 —— 这个选项可能不在 extUser.pdf 里，"
                       "去同目录别的书（extCmdRef 之类）找 **\n")
        ch.add("".join(blk))
    ch.flush()
    ch.report()
    print("\n把这些文件依次带出来即可。")


def cmd_toc(args):
    """扫全文里所有 '-option' 词元 + 首见页，输出很小，用来确认这本书对不对。"""
    work = args.get("work", WORK_DEFAULT)
    s, pages, starts = load(work)
    seen = {}
    pat = re.compile(r"(?<![\w-])-([a-z][a-z0-9_]{3,})\b")
    for pi, ptext in enumerate(pages):
        for m in pat.finditer(ptext):
            k = m.group(1)
            if k not in seen:
                seen[k] = [pi + 1, 0]
            seen[k][1] += 1
    minc = int(args.get("min", 2))
    items = sorted(seen.items(), key=lambda kv: -kv[1][1])
    ch = Chunker(work, "toc", int(args.get("budget", CHUNK_BYTES)))
    ch.add("# 全文出现过的 -option 词元（>=%d 次），按频次排序\n" % minc)
    for k, pc in items:
        if pc[1] < minc:
            continue
        ch.add("-%-40s %5d 次  首见 p.%d\n" % (k, pc[1], pc[0]))
    ch.flush()
    ch.report()


def cmd_grep(args):
    work = args.get("work", WORK_DEFAULT)
    s, pages, starts = load(work)
    terms = args.get("_pos", [])
    if not terms:
        die("用法: grep PATTERN [PATTERN...]")
    per_hit = int(args.get("per-hit", 900))
    max_hits = int(args.get("hits", 6))
    ch = Chunker(work, "grep", int(args.get("budget", CHUNK_BYTES)))
    for term in terms:
        hits, total = find_hits(pages, term, max_hits)
        ch.add("\n===== %s ===== (%d 命中, 取 %d)\n" % (term, total, len(hits)))
        for score, pg, ln, ctx in hits:
            c = collapse(ctx)
            if len(c) > per_hit:
                c = c[:per_hit] + " ...[截断]"
            ch.add("-- p.%d --\n%s\n" % (pg, c))
    ch.flush()
    ch.report()


def cmd_page(args):
    work = args.get("work", WORK_DEFAULT)
    s, pages, starts = load(work)
    pos = args.get("_pos", [])
    if not pos:
        die("用法: page N [M]   （倒出第 N..M 页原文）")
    a = int(pos[0])
    b = int(pos[1]) if len(pos) > 1 else a
    ch = Chunker(work, "page", int(args.get("budget", CHUNK_BYTES)))
    for i in range(a, b + 1):
        if 1 <= i <= len(pages):
            ch.add("\n========== p.%d ==========\n%s\n" % (i, pages[i - 1]))
    ch.flush()
    ch.report()


# --------------------------------------------------------------------------

def die(msg):
    sys.stderr.write("ERROR: %s\n" % msg)
    sys.exit(1)


def _u(x):
    """py2 hands us argv as byte str; everything downstream is unicode."""
    if isinstance(x, bytes):
        return x.decode("utf-8", "replace")
    return x


def parse_argv(argv):
    argv = [_u(x) for x in argv]
    args, pos = {}, []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a.startswith("--"):
            k = a[2:]
            if "=" in k:
                k, v = k.split("=", 1)
                args[k] = v
            elif k == "force":
                args[k] = True
            else:
                i += 1
                args[k] = argv[i] if i < len(argv) else ""
        else:
            pos.append(a)
        i += 1
    args["_pos"] = pos
    return args


CMDS = {"build": cmd_build, "info": cmd_info, "ask": cmd_ask,
        "toc": cmd_toc, "grep": cmd_grep, "page": cmd_page}


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help", "help"):
        print(__doc__)
        sys.exit(0)
    sub = sys.argv[1]
    if sub not in CMDS:
        die("未知子命令 %r，可用: %s" % (sub, ", ".join(sorted(CMDS))))
    a = parse_argv(sys.argv[2:])
    a.setdefault("work", WORK_DEFAULT)
    a.setdefault("pdf", PDF_DEFAULT)
    CMDS[sub](a)
