#!/usr/bin/env python3
"""Regenerate ``extdoc_probe.py``'s FIELDS table from the catalog.

``extdoc_probe.py`` runs in the RED ZONE, where there is no Auto_ext checkout
to import and the interpreter on PATH is Python 2.7. So its question list has
to be frozen into the file -- it cannot ask the catalog at run time.

Frozen is not the same as hand-maintained. Run this on the dev machine
whenever a ``question:`` is answered and deleted, or a new row grows one, and
commit the result. Left alone, the table drifts: the version recovered from
the August session was still asking twelve questions that had since been
answered, while sixteen rows that had opened since were not asked at all.

    python scripts/refresh_extdoc_fields.py         # rewrite in place
    python scripts/refresh_extdoc_fields.py --check # fail if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

TARGET = REPO_ROOT / "scripts" / "extdoc_probe.py"

#: Rows whose derived term would never hit. A row that emits nothing yet has
#: no landing site, so the fallback is ``-{template_var}`` -- a name we
#: invented, which the vendor's manual has never seen.
OVERRIDE: dict[str, list[str]] = {
    "global_nets_nets": ["global_nets", "-import_from_lvs", "-force_global_nets"],
    "strmout_hier_depth": ["strmout", "hierarchy depth"],
    "cdl_include_file": ["cdl_include_file", "includeFile"],
}


def build_table() -> tuple[str, int]:
    from auto_ext.catalog import builtin_catalog

    catalog = builtin_catalog()

    # An option name several rows share is not a search term: `-type` belongs
    # to extract, metal_fill, input_db and output_db alike, so searching it
    # bare finds all four and answers none. Counted per ROW, not per landing
    # site -- almost every Quantus option lands in both command files.
    seen: dict[str, int] = {}
    for opt in catalog.options:
        for name in {site.option for site in opt.lands_in if site.option}:
            seen[name] = seen.get(name, 0) + 1
    shared = {name for name, count in seen.items() if count > 1}

    rows = []
    for opt in catalog.options:
        if not opt.question:
            continue
        tools = sorted({catalog.tool_of(s.target) for s in opt.lands_in if s.target})
        tool = tools[0] if tools else "quantus(absent)"
        terms: list[str] = []
        for site in opt.lands_in:
            if not site.option:
                continue
            term = (
                f"{site.section} {site.option}"
                if site.option in shared
                else site.option
            )
            if term not in terms:
                terms.append(term)
        for fallback in (f"-{opt.template_var}", opt.template_var):
            if fallback not in terms:
                terms.append(fallback)
        terms = OVERRIDE.get(opt.key) or terms
        rows.append((tool, opt.key, terms, " ".join(opt.question.split())))
    rows.sort(key=lambda r: (r[0] not in ("quantus", "quantus(absent)"), r[0], r[1]))

    lines = [
        "FIELDS = [",
        "    # (key, [search terms], what we actually want to know)",
        "    #",
        "    # GENERATED by scripts/refresh_extdoc_fields.py from options.yaml --",
        "    # every row that still carries a `question:`. Do not edit by hand:",
        "    # a list maintained here drifts from the catalog the moment a",
        "    # question is answered, and then this script goes on asking things",
        "    # nobody needs while missing the ones nobody has asked.",
    ]
    current = None
    for tool, key, terms, question in rows:
        if tool != current:
            lines.append(f"    # ---- {tool} ----")
            current = tool
        lines.append(f"    ({key!r}, {terms!r},")
        lines.append(f"     {question!r}),")
    lines.append("]")
    return "\n".join(lines), len(rows)


def rewritten() -> tuple[str, int]:
    table, count = build_table()
    text = TARGET.read_text(encoding="utf-8")
    start = text.index("FIELDS = [")
    end = text.index("\n]", start) + len("\n]")
    return text[:start] + table + text[end:], count


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the frozen table is out of date",
    )
    args = parser.parse_args(argv)

    text, count = rewritten()
    if args.check:
        if text != TARGET.read_text(encoding="utf-8"):
            print(
                "extdoc_probe.py's FIELDS table is stale -- run "
                "scripts/refresh_extdoc_fields.py",
                file=sys.stderr,
            )
            return 1
        print(f"FIELDS is current ({count} open questions)")
        return 0

    TARGET.write_text(text, encoding="utf-8")
    print(f"{TARGET.name}: FIELDS regenerated, {count} open questions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
